services:
  - type: web
    name: yuktihire-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: MONGO_URI
      - key: JWT_SECRET
      - key: GOOGLE_GENAI_API_KEY
      - key: CLIENT_URL
      - key: NODE_ENV
        value: production

  - type: static
    name: yuktihire-frontend
    region: oregon
    plan: free
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: Frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
